apiVersion: v1
kind: Secret
metadata:
  name: {{ include "iceberg-catalog.fullname" . }}
  labels:
    {{- include "iceberg-catalog.labels" . | nindent 4 }}
type: Opaque
stringData:
    CATALOG_WAREHOUSE: {{ .Values.config.catalog_warehouse }}
    CATALOG_IO__IMPL: {{ .Values.config.catalog_impl }}
    AWS_ACCESS_KEY_ID: {{ .Values.config.aws_access_key }}
    AWS_SECRET_ACCESS_KEY: {{ .Values.config.aws_secret_key }}
    AWS_REGION: {{ .Values.config.aws_region }}
    CATALOG_S3_ENDPOINT: {{ .Values.config.s3_endpoint }}
    S3_PATH_STYLE_ACCESS: {{ .Values.config.s3_path_style | quote }}
    CATALOG_BACKEND: {{ .Values.config.catalog_backend }}
    CATALOG_JDBC__URL: {{ .Values.database.url }}
    CATALOG_JDBC__USER: {{ .Values.database.user | quote }}
    CATALOG_JDBC__PASSWORD: {{ .Values.database.password | quote }}
    
