# Default values for rss-reader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: larrywshields/rss-reader
  pullPolicy: Always
  tag: latest


service:
  type: NodePort
  port: 80
  nodeport: 30089


resources: 
  limits:
    cpu: 990m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 500Mi

application:
  profile: prd
  billprefix: 20210
  pollinterval: 60000
  database:
    url: jdbc:postgresql://localhost:5432/db
    platform: org.hibernate.dialect.PostgreSQLDialect
    user: ""
    password: ""
    connectionpool: 50
  