# Default values for rss-reader.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: larrywshields/rss-reader
  pullPolicy: Always
  tag: latest


service:
  type: NodePort
  port: 80
  nodeport: 30089


resources: 
  limits:
    cpu: 500m
    memory: 500Mi
  requests:
    cpu: 100m
    memory: 128Mi

application:
  profile: prd
  billprefix: 20210
  database:
    url: 
    platform: org.hibernate.dialect.PostgreSQLDialect
    user:
    password:
  