# Default values for bill-api.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: larrywshields/bill-api
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 8080
  nodeport: 30081


resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 256Mi
application:
  profile: prd

database:
    url: jdbc:postgresql://jenkins-build:5432/bills_db
    platform: org.hibernate.dialect.PostgreSQLDialect
    user: ""
    password: ""
    connectionpool: 20
  
