apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bill-api.fullname" . }}
data:
    DB_PLATFORM: {{ .Values.application.database.platform | quote }}
    DB_URL: {{ .Values.application.database.url | quote }}
    ACTIVE_PROFILE: {{ .Values.application.profile | quote }}
    DB_CONNECTION_POOL: {{ .Values.application.database.connectionpool | quote }}
