apiVersion: v1
kind: Secret
metadata:
  name: {{ include "bill-api.fullname" . }}
  labels:
    {{- include "bill-api.labels" . | nindent 4 }}
type: Opaque
stringData:
    DB_USER: {{ .Values.database.user | quote }}
    DB_PASSWORD: {{ .Values.database.password | quote }}
