# Default values for nfl-satst-api
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: larrywshields/nfl-stats-api:latest
  pullPolicy: Always
  tag: latest

service:
  type: NodePort
  port: 8080
  nodeport: 30082


resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 100m
    memory: 256Mi
application:
  profile: prd

database:
    url: jdbc:postgresql://jenkins-build:5432/nfl_stats
    platform: org.hibernate.dialect.PostgreSQLDialect
    user: ""
    password: ""
    connectionpool: 5
  
