
replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: LoadBalancer

database:
  name: postgres
  user: admin
  password: password
  port: 5432
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
storage:
  enabled: true
  class: longhorn
  name: postgres-db-store
  request: 2Gi

