
replicaCount: 1

image:
  repository: postgres
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: NodePort
  outport: 30432

database:
  name: bill_db
  user: bills_adm
  password: b!ll$_db
  port: 5432
resources:
  limits:
    cpu: 500m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 512Mi
storage:
  enabled: true
  class: longhorn
  name: postgres-billsdb-store
  request: 2Gi

