apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rss-reader.fullname" . }}
data:
    APP_BILL_PREFIX: {{ .Values.application.billprefix }}
    DB_PLATFORM: {{ .Values.application.database.platform }}
    DB_URL: {{ .Values.application.database.url }}
    ACTIVE_PROFILE: {{ .Values.application.profile }}
    APP_POLL_INTERVAL: {{ .Values.application.pollinterval }}
