apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "rss-reader.fullname" . }}
data:
    APP_BILL_PREFIX: {{ .Values.application.billprefix | quote }}
    DB_PLATFORM: {{ .Values.application.database.platform | quote }}
    DB_URL: {{ .Values.application.database.url | quote }}
    ACTIVE_PROFILE: {{ .Values.application.profile | quote }}
    APP_POLL_INTERVAL: {{ int64 .Values.application.pollinterval | quote }}
    DB_CONNECTION_POOL: {{ .Values.application.database.connectionpool | quote }}
    DB_DDL: {{ .Values.application.database.ddl | quote }}
