apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rss-reader.fullname" . }}
  labels:
    {{- include "rss-reader.labels" . | nindent 4 }}
type: Opaque
stringData:
    DB_USER: {{ .Values.application.database.user }}
    DB_PASSWORD: {{ .Values.application.database.password }}
